image: adoptopenjdk/openjdk11:jdk-11.0.10_9-ubuntu
    
stages:
  - build
  - test
  - quality
  - deploy
    
before_script:
#  - echo `pwd` # debug
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle
      
cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
    
build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/
      - actionfx-core/build/
      - actionfx-testing/build/
      - actionfx-controlsfx/build/
      - actionfx-spring-boot/build/
      - actionfx-app-sample/build/
    when: always
    expire_in: 1 week
    
unittest:
  stage: test
  script:
    - ./gradlew check
  artifacts:
    paths:
      - build/
      - actionfx-core/build/
      - actionfx-testing/build/
      - actionfx-controlsfx/build/
      - actionfx-spring-boot/build/
      - actionfx-app-sample/build/
    when: always
    expire_in: 1 week

integrationtest:
  stage: test
  script:
    - apt-get update && apt-get install -y libxtst6 libgtk2.0-0
    - ./gradlew integrationTest
  artifacts:
    paths:
      - build/
      - actionfx-core/build/
      - actionfx-testing/build/
      - actionfx-controlsfx/build/
      - actionfx-spring-boot/build/
      - actionfx-app-sample/build/
    when: always
    expire_in: 1 week
    
reportCodeCoverage:
  stage: quality
  script:
    - ./gradlew codeCoverageReport -x test
    - ./gradlew sonarqube -x test
  artifacts:
    paths:
      - build/
      - actionfx-core/build/
      - actionfx-testing/build/
      - actionfx-controlsfx/build/
      - actionfx-spring-boot/build/
      - actionfx-app-sample/build/
    when: always
    expire_in: 1 week

publishJavaDoc:
  stage: deploy
  when: manual
  variables:
    GRGIT_USER: ${GRGIT_USER}
    GRGIT_PASS: ${GRGIT_PASS}    
  script:
    - ./gradlew copyJavaDocToDocs -x test
    - ./gradlew gitPublishPush -x test 
    
releaseToMavenCentral:
  stage: deploy
  when: manual
  script:
    - ./gradlew publishAllPublicationsToSonatypeRepository closeAndReleaseSonatypeStagingRepository -x test 
  artifacts:
    paths:
      - build/
      - actionfx-core/build/
      - actionfx-testing/build/
      - actionfx-controlsfx/build/
      - actionfx-spring-boot/build/
      - actionfx-app-sample/build/
    when: always
    expire_in: 1 week
  
