image: adoptopenjdk/openjdk11:jdk-11.0.9.1_1-ubuntu
    
stages:
  - build
  - test
  - quality
    
before_script:
#  - echo `pwd` # debug
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle
    
cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
    
build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/
      - actionfx-core/build/
      - actionfx-testing/build/
      - actionfx-spring-boot/build/
      - actionfx-app-sample/build/
    expire_in: 1 week
    
unittest:
  stage: test
  script:
    - ./gradlew check
  artifacts:
    paths:
      - build/
      - actionfx-core/build/
      - actionfx-testing/build/
      - actionfx-spring-boot/build/
      - actionfx-app-sample/build/
    expire_in: 1 week
    
reportCodeCoverage:
  stage: quality
  script:
    - ./gradelw codeCoverageReport
    -  bash <(curl -s https://codecov.io/bash)
  artifacts:
    paths:
      - build/
      - actionfx-core/build/
      - actionfx-testing/build/
      - actionfx-spring-boot/build/
      - actionfx-app-sample/build/
    expire_in: 1 week
    