name: ActionFX Release Management

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "ActionFX Build Management" ]
    types:
      - completed

jobs:
  publish-javadoc:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: ./

      - name: Publish Javadoc
        run: |
          ./gradlew copyJavaDocToDocs gitPublishPush -x test --no-daemon
        env:
          GRGIT_USER: ${{ secrets.GRGIT_USER }}
          GRGIT_PASS: ${{ secrets.GRGIT_PASS }}

  release-to-maven-central:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: ./

      - name: Setup Signing Key
        run: |
          echo "signingKey=${{ secrets.SIGNING_KEY }}" >> $GITHUB_ENV
          echo "signingPassword=${{ secrets.SIGNING_PASSWORD }}" >> $GITHUB_ENV

      - name: Release to Maven Central
        run: ./gradlew publishAllPublicationsToSonatypeRepository closeAndReleaseSonatypeStagingRepository -x test --no-daemon
